package info.sjd;

import info.sjd.AppendFile;

/**
 * 
 * @author Vitaliy-tyma
 * 
 *
 *         DATA INPUT/OUTPUT
 * 
 *         DONE Create class for data saving process about server connection
 *         with the following fields: time (current system time), session and
 *         IP.
 * 
 *         DONE Create list of 10 instances of this class through implementation
 *         of log recordings //—оздать список из 10 экземпл€ров этого класса
 *         через реализацию записи логов
 * 
 *         DONE Fields are to be generated by your own, better to implement own
 *         randomizer for values range. //ѕол€ генерируем сами, лучше написать
 *         свой рандомайзер дл€ диапазона значений.
 * 
 *         DONE Record data from the list into TXT file in LOG folder inside of
 *         the project. //«аписать данные из списка в txt файл в папку log
 *         внутри проекта.
 * 
 *         DONE Previous records in the file must be preserved. //ѕредыдущие
 *         записи в файле должны быть сохранены.
 * 
 *         DONE As a result file has to contain such data: 1529666255304
 *         123456789 128.158.234.15 1529666289304 123456799 123.148.214.19 Е
 *         First column is time in milliseconds, Second - session (random
 *         9-digits number), Third - IP (also is created by randomly). //√де
 *         перва€ колонка Ц врем€ в миллисекундах, //втора€ Ц сесси€ (рандомное
 *         дев€тизначное число), //треть€ Ц IP (тоже создаетс€ рандомно)
 * 
 * 
 *         DONE Implement logs recording //—оздать реализацию записи логов
 * 
 *         DONE Implement connections logs reading from this file for some
 *         period //—оздать реализацию считывани€ логов подключени€ из этого
 *         файла за период
 * 
 *         DONE Implement logs deleting from files older then 3 days. //—оздать
 *         реализацию удалени€ логов из файлов старше 3-х дней
 * 
 */

public class AppRunner {

	/* MAIN ****************************************/
	public static void main(String[] args) {

		/** INITIALISATION */
		final String DIR_NAME = "log/";
		final String FILE_NAME = DIR_NAME + "task08.txt";

		/** Save logs to file. */
		AppendFile.appendFile(FILE_NAME);

		/** Read logs from file. Print logs to the logger. */
		ReadFile.readFile(FILE_NAME);

		/** Delete 3 days older records from the log-file. */
		DelOldRecords.delOldRecords(FILE_NAME);

	}

}